[parity]
chain = "/openethereum/genesis.json" 
base_path = "/openethereum/" 

[network]
port = 30316
reserved_peers=  "/openethereum/nodes" 
allow_ips = "all"
discovery = true

[rpc]
port = 8648
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[websockets]
disable = false
port = 10647
interface = "all"
origins = ["none"]
apis = ["all"]
hosts = ["all"]

[account]
password = ["/openethereum/password"] 

[mining]
engine_signer = "0x72d6424dbc29fc63eda6af9742d0ebadb57717c6"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/openethereum/log.log"
color = true
